/* Generated By:JavaCC: Do not edit this line. TinyBasicParserConstants.java */
package fr.utbm.info.da53.lw2.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface TinyBasicParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NUMBER = 4;
  /** RegularExpression Id. */
  int ID = 5;
  /** RegularExpression Id. */
  int STRING = 6;
  /** RegularExpression Id. */
  int CR = 7;
  /** RegularExpression Id. */
  int PLUS = 8;
  /** RegularExpression Id. */
  int MINUS = 9;
  /** RegularExpression Id. */
  int MULT = 10;
  /** RegularExpression Id. */
  int DIV = 11;
  /** RegularExpression Id. */
  int PRINT = 12;
  /** RegularExpression Id. */
  int LET = 13;
  /** RegularExpression Id. */
  int GOTO = 14;
  /** RegularExpression Id. */
  int IF = 15;
  /** RegularExpression Id. */
  int THEN = 16;
  /** RegularExpression Id. */
  int END = 17;
  /** RegularExpression Id. */
  int REM = 18;
  /** RegularExpression Id. */
  int INPUT = 19;
  /** RegularExpression Id. */
  int GOSUB = 20;
  /** RegularExpression Id. */
  int RETURN = 21;
  /** RegularExpression Id. */
  int LD = 22;
  /** RegularExpression Id. */
  int LE = 23;
  /** RegularExpression Id. */
  int EQ = 24;
  /** RegularExpression Id. */
  int NE = 25;
  /** RegularExpression Id. */
  int GE = 26;
  /** RegularExpression Id. */
  int GD = 27;
  /** RegularExpression Id. */
  int LEFT_PAREN = 28;
  /** RegularExpression Id. */
  int RIGHT_PAREN = 29;
  /** RegularExpression Id. */
  int DQ = 30;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "<NUMBER>",
    "<ID>",
    "<STRING>",
    "\"\\n\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"PRINT\"",
    "\"LET\"",
    "\"GOTO\"",
    "\"IF\"",
    "\"THEN\"",
    "\"END\"",
    "\"REM\"",
    "\"INPUT\"",
    "\"GOSUB\"",
    "\"RETURN\"",
    "\"<\"",
    "\"<=\"",
    "\"=\"",
    "<NE>",
    "\">=\"",
    "\">\"",
    "\"(\"",
    "\")\"",
    "\"\\\"\"",
  };

}
